### ISSUE TITLE
How do invites to Privacytools.io hosted services work?

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/services#12]
I have no idea how the invites to Writeas, Mastodon and whatever else work, while they are at times asked about. Which people have permissions to invite and are there team accounts which only purpouse is to invite people?

**Comment by JonahAragon** [comment]
**Mastodon: https://social.privacytools.io/invites (anyone can invite)
WriteFreely: https://write.privacytools.io/me/invites (anyone can invite)
Blog: Manual approval process (by me)**
Matrix: open
Mail: team members only
Discourse: open
PrivateBin: no accounts
Gitea: open

We should not be invite-only on any other service. Users can email support@privacytools.io for the shared-team inbox, and any of us can reply with an invite link as needed.
