### ISSUE TITLE
Search Feature Not Working

### ISSUE THREAD

**Issue by Marc05** [privacytoolsIO/services#21]
![Annotation 2020-02-21 211157](https://user-images.githubusercontent.com/1699133/75084605-0d114380-5519-11ea-8554-4481f12d05af.png)

When using the search feature on the main page, it sometimes returns a 500 internal server error. Other times, it loads a global internet search instead of keeping the site scope:

![Annotation 2020-02-21 211850](https://user-images.githubusercontent.com/1699133/75084697-adfffe80-5519-11ea-9931-1ef93ab464b9.png)

**Comment by jonaharagon** [comment]
> Other times, it loads a global internet search instead of keeping the site scope:

This is intentional behavior: It isn't supposed to search the site.

**Comment by jonaharagon** [comment]
Should be fixed 🤞
