### ISSUE TITLE
Gitea: 502 Bad Gateway ~ nginx

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/services#25]
**Service**
What service are you trying to access?

https://git.privacytools.io/

**Describe the issue**
A clear and concise description of what the issue is. Please include any error messages you see in your browser/app/etc.

```
502 Bad Gateway
nginx
```

**Demographics**
Your country: se13-wireguard
Your ISP: Mullvad.net

**Screenshots**

![kuva](https://user-images.githubusercontent.com/831184/77352876-98643b80-6d48-11ea-8a8e-84f89454db71.png)

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Browser Firefox
 - Version 68.6.0esr (64-bittinen)

**Smartphone (please complete the following information):**

**Additional context**

I don't think this issue template is very useful.

**Comment by jonaharagon** [comment]
Yep, something has been wrong with Gitea 😕 It'll be fixed in a few hours.
