### ISSUE TITLE
Status page is using CDT instead of UTC or local time

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/services#28]
**Service**

status.privacytools.io / privacytools.statuspage.io

**Describe the bug**

The status page is using a timezone called "CDT" instead of the international timezone standard, [Coordinated Universal TIme (UTC)](https://en.wikipedia.org/wiki/Coordinated_Universal_Time) leading to confusion when visitors have no idea what is CDT.

**To Reproduce**

1. Go to https://status.privacytools.io/ / https://privacytools.statuspage.io/ without knowing what is CDT or its offset to your local time.
2. Look at any timestamp
3. Wonder what that is in local time.

**Expected behavior**

All timestamps are either in UTC or in the local time reported by my web browser, so as someone who has to think international times can calculate the offset to local time easily and have an idea what the time is or I can directly see it in local time.

**Screenshots**

![Matrix situation with timestamps in CDT](https://user-images.githubusercontent.com/831184/79052150-298a4c00-7c3d-11ea-9d74-e8dc33084b68.png)

![Scheduled maintenances in CDT](https://user-images.githubusercontent.com/831184/79052169-44f55700-7c3d-11ea-8d20-1582c07f33aa.png)

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux bullseye/sid
 - Browser: Firefox
 - Version: 75.0 64-bit 

**Additional context**

Using non-UTC timezone in a big international project or where audience is international just doesn't work. It's not realistic for everyone to learn all timezone abbreviations and their offsets if every project was using their own time instead of UTC.

UTC time can easily be gotten by `date -u` command. [UTC time in international date formating (ISO 8601)](https://en.wikipedia.org/wiki/ISO_8601) can be gotten with `date -Is -u`.

**Comment by jonaharagon** [comment]
Fine

**Comment by Mikaela** [comment]
Thank you :purple_heart:
