### ISSUE TITLE
https://search.privacytools.io/ needs to be updated.

### ISSUE THREAD

**Issue by romulasry** [privacytoolsIO/services#31]
**Service**
I am noticing an issue on https://search.privacytools.io/ 

**Describe the bug**
The bug is:

Engines cannot retrieve results:
gigablast (unexpected crash: extra param expired, please reload), yahoo (unexpected crash: list index out of range)

**To Reproduce**
1. Go to https://search.privacytools.io/ 
2. Click on type in test
3. Look at top right

**Expected behavior**
Search results without the errors

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Clear Linux
 - Browser: Firefox
 - Version: 77.0.1

**Smartphone (please complete the following information):**
N/A

**Additional context**
See more info here on the searx instance: https://github.com/privacytools/search/issues/10

**Comment by foresto** [comment]
There's a similar problem with the Google engine. Google results are missing and this error message appears in the sidebar:

    Engines cannot retrieve results:
    google (unexpected crash CAPTCHA required)

**Comment by romulasry** [comment]
0.17.0 was just released: https://github.com/privacytools/search/issues/12
