### ISSUE TITLE
search rate limit exceeded

### ISSUE THREAD

**Issue by foresto** [privacytoolsIO/services#35]
**Service**
https://search.privacytools.io/

**Describe the issue**
As of today, searches started failing with the following message:
Rate limit exceeded

**Comment by foresto** [comment]
The error occurs when I search from the Firefox addres bar (with PrivacyTools Search as my default search engine), but not if I use the web form on search.privacytools.io.

**Comment by romulasry** [comment]
Same bug, interested in when it will get fixed.

**Comment by ghost** [comment]
I have the same issue. No matter when I search, what I search, or how often I search using the Firefox address bar, I get this error.

Going to search.privacytools.io and searching works fine.

**Comment by jonaharagon** [comment]
Appears to be fixed (with #31?), or cannot reproduce.
