### ISSUE TITLE
🌐 Website Issue | Discourse Recommends Google

### ISSUE THREAD

**Issue by ggg27** [privacytoolsIO/services#7]
**Description**: Discourse *\*appears** to be recommending Google.

I will assume that PTIO isn't do this or receiving any funding (correct?).
But, I did want to bring up a discussion on possibly changing this to [Jive Search](http://jivesearch.com/).

Perhaps PTIO could create an issue on their [bug tracker](https://github.com/discourse/discourse) as well?

## Screenshots

![Screenshot at 2019-08-21 19:39:51](https://user-images.githubusercontent.com/52841257/63481801-4263a880-c486-11e9-968f-13b7088bc3b1.png)

Please add screenshots if applicable

**Comment by JonahAragon** [comment]
This is an upstream issue.
