### ISSUE TITLE
Gitea is missing branding and running an old version (and not defaulting to dark theme)

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/services#9]
https://git.privacytools.io/ calls itself as " PrivacytoolsIO Git" while our branding is "PrivacyTools" and I guess it could also say Gitea. I think @dawidpotocki has also requested it to have our logo on the front page.

It's currently running 1.9.0 while the current version of GItea is v1.10.1 released ~two weeks ago.

Additional request: could it use dark theme by default (that can be overridden by logged in user in settings)? That would be done by adding the following to Gitea's `app.ini`.

```ini
[ui]
DEFAULT_THEME = arc-green
```

**Comment by Mikaela** [comment]
Running version: 1.9.0
Current version: v1.11.1

* https://github.com/go-gitea/gitea/releases/

**Comment by jonaharagon** [comment]
I've heard a lot of feedback (wrt the forum theme) *against* dark theme by default recently.

**Comment by Mikaela** [comment]
I hope that doesn't still prevent upgrading it
